# Generated by Django 4.2.5 on 2023-09-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_notes_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='date',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
